name: Deploy frontend to Cloudflare Pages

on:
    push:
        branches:
            - "main"
    workflow_dispatch:

permissions:
    contents: read
    deployments: write

defaults:
    run:
        working-directory: "frontend/"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout Repo"
              uses: "actions/checkout@v4"

            - name: "Setup NodeJS"
              uses: "actions/setup-node@v4"
              with:
                  "node-version": "26"

            - name: "Install Deps"
              run: "npm ci"

            - name: "Build"
              run: "npm run build"
              env:
                  "NEXT_PUBLIC_API_URL": ${{vars.NEXT_PUBLIC_API_URL}}

            - name: "Deploy to CloudFlare"
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  command: pages deploy frontend/out --project-name=esco
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
